### ISSUE TITLE
Trace breaks at message subscriber boundary

### ISSUE THREAD

**Issue by bluetentacle** [signalfx/signalfx-dotnet-tracing#176]
**Describe the bug**
I'm evaluating Splunk APM for my company. I set up 5 sample .NET Core services which talk to each other using HTTP, RabbitMQ, and Kafka. I'm noticing that even though the APM agent is able to correctly detect all spans, a new trace is always started when a message subscriber receives a message. I expected there to be a single, continuous trace linking all services.

**To Reproduce**
Create the following .NET Core services, all running in Linux containers, that communicate with each other in a chain:

```
client
  -http->InboundRouter
           -kafka->CallManager
                     -rabbitmq->CallLogger
                                 -http->LeadManager
                                          -rabbitmq->LeadNotifier
```

...and invoke the HTTP endpoint `POST /v1/tenants/?/calls` on InboundRouter

For every call on InboundRouter, I'm seeing three traces being created, whose initial operations are:

- inbound-router: POST /v1/tenants/?/calls
- call-manager: POST POST
- call-logger: insert

**Expected behavior**
A single trace should be created containing activity on all five services.

**Screenshots**

Trace started by `inbound-router: POST /v1/tenants/?/calls`:
![image](https://user-images.githubusercontent.com/1126817/138368866-17166fca-fff4-4c2a-923e-68d9510e6966.png)

Trace started by `call-manager: POST POST`:
![image](https://user-images.githubusercontent.com/1126817/138368928-cef1fecf-2e48-4905-825e-a5117b5fccd8.png)

Trace started by `call-logger: insert`:
![image](https://user-images.githubusercontent.com/1126817/138368966-a8d615cc-32e2-4630-a3b3-92f1607e8b04.png)

**Comment by pjanotti** [comment]
Hi @bluetentacle - we area adding the initial code to automate publication of releases. You will find a build under my github user at https://github.com/pjanotti/signalfx-dotnet-tracing/releases/tag/v0.0.1

I didn't verify directly your scenario but per @RassK this should fix the issue. Let's know if that is not the case and we will look at the issue. The configuration uses the same environment variables that you are already using with the addition of:

```terminalSIGNALFX_EXPORTER="Zipkin"

**Comment by pjanotti** [comment]
Hi @bluetentacle - we area adding the initial code to automate publication of releases. You will find a build under my github user at https://github.com/pjanotti/signalfx-dotnet-tracing/releases/tag/v0.0.1

I didn't verify directly your scenario but per @RassK this should fix the issue. Let's know if that is not the case and we will look at the issue. The configuration uses the same environment variables that you are already using with the addition of:

```terminal
export SIGNALFX_EXPORTER="Zipkin"

**Comment by pjanotti** [comment]
Hi @bluetentacle - we area adding the initial code to automate publication of releases. You will find a build under my github user at https://github.com/pjanotti/signalfx-dotnet-tracing/releases/tag/v0.0.1 (this is under my github because we still have to update version and full notes before starting to publish from the next-ver).

I didn't verify directly your scenario but per @RassK this should fix the issue. Let's know if that is not the case and we will look at the issue. The configuration uses the same environment variables that you are already using with the addition of:

```terminal
export SIGNALFX_EXPORTER="Zipkin" 
export SIGNALFX_PROPAGATORS="b3"
export SIGNALFX_TRACE_AGENT_URL=${SIGNALFX_TRACE_AGENT_URL:-"http://localhost:9411/api/v2/spans"}
```

For a complete setup check the docker compose and related files at https://github.com/signalfx/signalfx-dotnet-tracing/tree/next-ver/dev

**Comment by bluetentacle** [comment]
Hi @pjanotti . Thanks for notifying me. I'll give it a try.

**Comment by bluetentacle** [comment]
Hi @pjanotti 

I tested the new agent and it now correctly links all the services into a single trace. However, a new problem has surfaced: 

![image](https://user-images.githubusercontent.com/1126817/143662048-889587f6-080c-4548-98a5-0c0be62076ff.png)

As you can the span names no longer contain the resource names. For inbound-router, for instance, the original agent included the path template `/v1/tenants/?/calls` and the Kafka topic `dev1.local.examples-telephony-inboundRouter.incomingCall` in the span names. Now, the span names are simply `HTTP POST` and `kafka.produce`. The ideal span name is a combination of the two. Here's a table listing the expected workflow names:

|service|original span name|new span name|ideal span name|
|-------|--------------------------|----------------------|-----------------------|
|inbound-router|/v1/tenants/?/calls|HTTP POST|HTTP POST /v1/tenants/?/calls|
|inbound-router|dev1.local.examples-telephony-inboundRouter.incomingCall send|kafka.produce|kafka.produce dev1.local.examples-telephony-inboundRouter.incomingCall|
|call-manager|dev1.local.examples-telephony-inboundRouter.incomingCall receive|kafka.consume|kafka.consume dev1.local.examples-telephony-inboundRouter.incomingCall|
|call-manager|POST|POST|HTTP POST http://lead_manager/v1/tenants/?/leads|
|call-manager|amq.topic send|amq.topic send|amq.topic send examples.telephony.callmanager.incomingcall.received|
|lead-manager|/v1/tenants/?/leads|HTTP POST|HTTP POST /v1/tenants/?/leads|
|lead-manager|amq.topic send|amq.topic send|amq.topic send examples.telephony.leadmanager.lead.created|
|lead-notifier|amq.topic receive|amq.topic receive|amq.topic receive examples.telephony.leadmanager.lead.created|

**Comment by pjanotti** [comment]
@bluetentacle thanks for getting back. I was on a break and will take a look at this later today.

**Comment by Kielek** [comment]
#231 will introduce changes in the related span names.

**Comment by lachmatt** [comment]
@bluetentacle can you share details about endpoint/routing configuration for ASP.NET CORE? Are there any middleware pipeline branches?

**Comment by pjanotti** [comment]
@bluetentacle 

Thanks for pointing these out. Some of them are really bugs others are deliberate decisions but looking forward to improve or change them. For some of them we are trying to be a bit more aligned with OpenTelemetry so we can facilitate an eventual transition from our own implementation to a pure OpenTelemetry one. Notice that some of the OpenTelemetry specs are still experimental so we have time to perhaps push for some changes.

Let me start with the "messaging related" ones, ie.: Kafka and RabbitMQ. For these two we are trying to align with the [span names recommended by OpenTelemetry](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#span-name). They will approximate your preference but will lack the "messaging system" on the span name. Notice that our backend will show the system inferred from the [corresponding span tag](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#messaging-attributes). I created issue to track changing these names: https://github.com/signalfx/signalfx-dotnet-tracing/issues/232

For the HTTP ones @lachmatt is trying to understand why the spans are not getting the route information. The change from the current version is due to the fact that we are trying to avoid high-cardinality names for spans (so metrics become more meaningful). The algorithm that replaces the original path with `?` is a bit "risky" in the sense that it recognizes numbers and GUIDs as high-cardinality and replace them with the `?`. However, many other high-cardinality names, eg.: track names, case sensitive ids, etc, are not captured by this simple algorithm so we are considering disabling it by default, or having some other option to control it.

Let's know your thoughts regarding these.

**Comment by bluetentacle** [comment]
Hi @pjanotti,

WRT messaging span names, we are happy as long as the topic is in the name. All other things are secondary.

As for HTTP, there's no need to "guess" which segments of the path is dynamic. Our .NET services don't use MVC but they do use ASP.NET Core's Routing library which has support for path templates. Datadog's open source agent is capable of reading the path templates for both MVC and Routing. Your code can do the same. See their method OnRoutingEndpointMatched: https://github.com/DataDog/dd-trace-dotnet/blob/88cd2a419869e931436c9434bd61c41e37ef45b4/tracer/src/Datadog.Trace/DiagnosticListeners/AspNetCoreDiagnosticObserver.cs#L575

**Comment by lachmatt** [comment]
Hi @bluetentacle,
There is `SIGNALFX_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED` environment variable that controls whether span name is updated in `OnRoutingEndpointMatched` method. 
Can you rerun your tests with flag set? It was recently changed to be enabled by default.

**Comment by bluetentacle** [comment]
@lachmatt I set SIGNALFX_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED=true but it's not working.

I think this is because the build of next-ver that @pjanotti gave me (https://github.com/pjanotti/signalfx-dotnet-tracing/releases/tag/v0.0.1) is rather old. The Datadog part was last updated 16 months ago.

To recap: the reason we are using next-ver is to address the "Trace breaks at message subscriber boundary" issue at the top of the thread.

When can I expect a new build from the latest next-ver code? Thanks.

**Comment by RassK** [comment]
@bluetentacle @pjanotti @lachmatt Let's finalize https://github.com/signalfx/signalfx-dotnet-tracing/pull/235 and create a new temp release after that. I think @bluetentacle is right, the first focus was to check propagation, unfortunately these PRs that reworked HTTP span names came later.

**Comment by bluetentacle** [comment]
Folks, I think the problem is on my end. The Datadog agent does have a code path to "guess" at the dynamic segments in UriHelpers.GetCleanUriPath and the latest agent is no longer relying on it, which is the correct thing to do. It turned out that the agent's support for Microsoft.AspnetCore.Routing only kicks in if we used the UseRouting or UseEndpoints extension methods to build out the routes. These methods register the EndpointRoutingMiddleware which invokes the "Microsoft.AspNetCore.Routing.EndpointMatched" event. But we are using the older UseRouter method, which does not invoke that event.

The solution would be to upgrade our code to use `UseRouting` or `UseEndpoints`, so that OnRoutingEndpointMatched method can be hit. I'll keep you updated on my progress.

**Comment by bluetentacle** [comment]
I'm here to report that converting to UseRouting/UseEndpoints worked. ASP.NET Core REST spans now show up with path templates rather than literal paths: 
![image](https://user-images.githubusercontent.com/1126817/146075929-a2907e87-2b35-4f0c-8a80-c9e2b7614f45.png)

**Comment by Kielek** [comment]
@bluetentacle, great to hear that. Thank you for an update. I will close this issue. Please let us know if you need any help.
